=== Coffee Cup Bread

1 Tablespoon butter
1/3 cup almond flour
1 egg
1/2 teaspoon baking powder
1 pinch salt

https://kirbiecravings.com/keto-low-carb-mug-bread/

=== Fathead recipe

General purpose dough

https://www.ditchthecarbs.com/fat-head-pizza/

1 3/4 cups pre shredded/grated cheese mozzarella is the best or Edam/mild cheese
3/4 cups almond meal/flour
2 tbsp cream cheese
1 egg
pinch salt to taste
1/2 tsp dried rosemary/ garlic or other flavourings optional
your choice of toppings such as pepperoni peppers, cherry tomatoes, olives, ground/mince beef, mushrooms, herbs etc


Instructions

1. Mix the shredded/grated cheese and almond flour/meal in a microwaveable bowl.
2. Add the cream cheese. Microwave on HIGH for 1 minute.
3. Stir then microwave on HIGH for another 30 seconds.
4. Add the egg, salt, rosemary and any other flavourings, mix gently.
5. Place in between 2 pieces of baking parchment/paper and roll into a circular pizza shape (see photos above). Remove the top baking paper/parchment. If the mixture hardens and becomes difficult to work with, pop it back in the microwave for 10-20 seconds to soften again but not too long or you will cook the egg.
6. Make fork holes all over the pizza base to ensure it cooks evenly.
7. Slide the baking paper/parchment with the pizza base, on a baking tray (cookie tray) or pizza stone, and bake at 220C/425F for 12-15 minutes, or until brown.
8. To make the base really crispy and sturdy, flip the pizza over (onto baking paper/parchment) once the top has browned.
9. Once cooked, remove from the oven and add all the toppings you like. Make sure any meat is already cooked as this time it goes back into the oven just to heat up the toppings and melt the cheese. Bake again at 220C/425F for 5 minutes.

Pizza


Cauliflower crust

Coconut flour crust