
== Dessert

nothing yet

=== Keto mousse

TDB

=== Chocolate Peanut Butter Fat Bombs

TBD

=== Brownies

Unverified

Ingredients:

11 tbsp unsalted butter
2oz / 4tbsp unsweetened dark chocolate or sugar free dark chocolate chips
3 eggs
1/2tsp vanilla extract
1/4 tsp almond extract
1/4 cup cocoa powder
1/2 cup almond flour
1/2 tsp baking powder
1 tbsp instant coffee
1/2 cup granulated monk fruit sweetener
1/3 cup powdered monk fruit sweetener
1/3 cup sugar free dark chocolate chips (I used bake believe)

Directions:

- Line a 8x8 glass baking pan with parchment paper
- combine almond flour, cocoa powder, baking powder, instant coffee and granulated sweetener together in a small bowl
- Melt butter and chocolate together in a larger bowl for 1 minute and whisk together
- Whisk in powdered sweetener, extracts & eggs
- whisk in the dry ingredients until just combined
- fold in chocolate chips and pour into baking pan
- bake at 350 for 20-22mins. Let cool until COMPLETELY cool. They will be super fudgy and break apart easily.

Taken from https://www.reddit.com/r/ketorecipes/comments/di072g/keto_fudgy_brownies/
